### PR TITLE
Feature/upload to s3

### PR DESCRIPTION
**Pull request by xiao-maven**

### CODE REVIEW

**Comment by xiao-maven** [comment]
tested locally by
- running a scentsy scrape, limited to 10 products
- `rake persist_unpersisted_images`
- checking the images loading and loading from s3

**Comment by xiao-maven** [comment]
@phil-monroe one more minor update in addition to recording file size:
- allow persisting to staging bucket rather than production bucket (though in theory uuid collisions shouldn't happen anyways...)

**Comment by xiao-maven** [comment]
scentsy scrape is going: https://maven-autobot-stg.herokuapp.com/admin/jobs/8a5d8875-413e-4451-9437-5f066580d86e. Should finish by 7:30

went ahead and persisted the existing images. can't actually get any s3 pulls though... mostly been seeing cloudflare `REVALIDATED` responses, which I assume is based purely on etag. not sure if cloudflare will end up passing through maven headers if it encounters them

**Comment by xiao-maven** [comment]
managed to get a cloudflare miss from staging;
screen shot 2018-02-28 at 19 56 39
 can verify at least one image coming from s3

**Comment by xiao-maven** [comment]
running `rake persist_unpersisted_images` on stage once more...

**Comment by phil-monroe** [comment]
Was able to see misses and things seem to look great in the browser. Going to walk through the app now.

Also, comparing the MD5s for a random image served from images and scentsy show a match :)
```
MD5 (original.png) = 36f6eabee46e91c2cfb452382195a164
MD5 (saved.png) = 36f6eabee46e91c2cfb452382195a164
```

**Comment by xiao-maven** [comment]
hmmm... probably going to want to put in some kind of handling for images that repeatedly fail fetch... the 404 test image here will be triggering warnings every persistence run once I get the proper bugsnag api keys in

```
Xiaos-MacBook-Pro:~/code/images(feature/upload-to-s3|✔)% heroku run rake persist_unpersisted_images -r stg
Running rake persist_unpersisted_images on ⬢ maven-images-stg... up, run.8231 (Hobby)
W, [2018-03-01T03:58:45.046137 #4]  WARN -- : No valid API key has been set, notifications will not be sent
D, [2018-03-01T03:58:45.862538 #4] DEBUG -- :   Image Load (5.5ms)  SELECT  "images".* FROM "images" WHERE "images"."persisted_to_s3" = $1 ORDER BY "images"."id" ASC LIMIT $2  [["persisted_to_s3", "f"], ["LIMIT", 1000]]
time=2018-03-01T03:58:45.910Z l=INFO msg="fetching image" url="https://imagelive.scentsy.com:443/cmsimages/products/rahomestargazediffusershadeunlitiso012ss18.png"
D, [2018-03-01T03:58:46.137029 #4] DEBUG -- :    (4.4ms)  BEGIN
D, [2018-03-01T03:58:46.167527 #4] DEBUG -- :   SQL (25.4ms)  UPDATE "images" SET "last_fetched_at" = $1, "updated_at" = $2 WHERE "images"."id" = $3  [["last_fetched_at", "2018-03-01 03:58:46.131986"], ["updated_at", "2018-03-01 03:58:46.139213"], ["id", "062ca254-e17b-4e84-9d4b-ed3a7b63b347"]]
D, [2018-03-01T03:58:46.171249 #4] DEBUG -- :    (2.1ms)  COMMIT
D, [2018-03-01T03:58:46.284288 #4] DEBUG -- :    (3.0ms)  BEGIN
D, [2018-03-01T03:58:46.288543 #4] DEBUG -- :   SQL (1.8ms)  UPDATE "images" SET "updated_at" = $1, "persisted_to_s3" = $2 WHERE "images"."id" = $3  [["updated_at", "2018-03-01 03:58:46.285034"], ["persisted_to_s3", "t"], ["id", "062ca254-e17b-4e84-9d4b-ed3a7b63b347"]]
D, [2018-03-01T03:58:46.292516 #4] DEBUG -- :    (3.2ms)  COMMIT
time=2018-03-01T03:58:46.292Z l=INFO msg="fetching image" url="http://httpstat.us/404"
D, [2018-03-01T03:58:46.461208 #4] DEBUG -- : Not notifying due to an invalid api_key
time=2018-03-01T03:58:46.461Z l=WARN msg="failed to fetch remote image" image=4d74a5e0-07c1-4b3c-bc72-433c008a30b8 reason="resp.code: 404"
time=2018-03-01T03:58:46.461Z l=INFO msg="fetching image" url="https://imagelive.scentsy.com:443/cmsimages/products/rahomeholidaydiffusershadeisofw17.png"
D, [2018-03-01T03:58:46.671809 #4] DEBUG -- : Not notifying due to an invalid api_key
time=2018-03-01T03:58:46.678Z l=WARN msg="failed to fetch remote image" image=5eb89ae6-7bd7-472f-984e-8ba86c9d5585 reason="resp.code: 404"
```

**Pull request merged**
